os: linux
sudo: false
language: python

matrix:
  include:
    - python: '2.7'
      env: TOXENV=py

    - python: '3.6'
      env: TOXENV=py

before_install:
  - uname -a
  - which python || true
  - which python2 || true
  - which python3 || true
  - which python;
    python --version
  - easy_install --version
  - pip --version

install:
  - pip install tox

script:
  - python -m tox -v

after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat

after_success:
  - pip install codecov
  - codecov

cache:
  - pip

branches:
  only:
    - master
    - /^.*-feature$/
    - /^.*-maintenance$/

notifications:
  email:
    # Select always or never
    on_success: always
    on_failure: always
